### ISSUE TITLE
[Feature 6] <workout data analysis>

### ISSUE THREAD

**Issue by bdls-jamal** [CSC207-2022F-UofT/course-project-git_gud#4]
Feature for the user to be able to look at data analytics of their workouts and track their progression.

**Comment by tejcapildeo** [comment]
Due date: November 14th 

Reviewers:
Clean Architecture and SOLID Principles - @turne142 
Test Coverage - @absolute-xero7 
Coding Style- @bdls-jamal 
Javadoc - @AHui156
