### ISSUE TITLE
[Feature 7] <target: add, delete, edit, view>

### ISSUE THREAD

**Issue by bdls-jamal** [CSC207-2022F-UofT/course-project-git_gud#5]
Feature to set goals and track progression of previously set goals.

**Comment by jhalaksaraogi** [comment]
Due Date: Nov 14th
Clean Architecture - @ivyparc @absolute-xero7 
Test Coverage - @turne142 
Coding Style- @tejcapildeo 
Javadoc - @bdls-jamal
